In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np

In [ ]:
#checking version of numpy
np.version.version

'1.26.4'

In [ ]:
#create 1d array
l=range(1,10)
l2=np.array(l)
print(l2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(type(l2))

<class 'numpy.ndarray'>


In [ ]:
# Q3: how to create a boolean array
l2=range(1,10)
l=np.array(l)
for i in range(1,9):
    if l[i]%2==0:
        l[i]=0
    else:
        l[i]=1

print(l)

[1 0 1 0 1 0 1 0 1]


In [ ]:
l3=np.array(l)
print(l3)

[1 0 1 0 1 0 1 0 1]


In [ ]:
#q4:How to reshape a array
l3.reshape(3,3)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [ ]:
l.reshape(3,3)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [ ]:
#q5 vertical stacking of l and l3
c=np.vstack((l,l3))
print(c)

[[1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]]


In [ ]:
print(c)

In [ ]:
#q6 horizontal stacking of l and l3
d=np.hstack((l,l3))

In [ ]:
print(d)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1]


In [ ]:
#q7 find sum of l and l3
l4=l+l3
print(l4)
l4=l4.reshape(3,3)
l4

[2 0 2 0 2 0 2 0 2]


array([[2, 0, 2],
       [0, 2, 0],
       [2, 0, 2]])

In [ ]:
#q8: find dot product of l3,l4
l5=l3.dot(l)
print(l5)

5


In [ ]:
l3new=l3.reshape(3,3)

In [ ]:
#q9: find dimension of l,l3,l3new
print(l.ndim,l3.ndim,l3new.ndim)


1 1 2


In [ ]:
#q10 find item size of l3new, and its datatype
print(l3new)
print(l3new.itemsize)
print(l3new.dtype)

[[1 0 1]
 [0 1 0]
 [1 0 1]]
8
int64


l3

In [ ]:
#q10: give a demo code of diff between size and shape and type conversion
l=range(0,100)
l2=np.array(l).reshape(50,2)
# print(l2)
print(l2.size)
l2.shape
l2float=np.array(l2,dtype=np.float64)
# print(l2float)
l2complex=np.array(l2,dtype=complex)

# print(l2complex)

100
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]
 [24. 25.]
 [26. 27.]
 [28. 29.]
 [30. 31.]
 [32. 33.]
 [34. 35.]
 [36. 37.]
 [38. 39.]
 [40. 41.]
 [42. 43.]
 [44. 45.]
 [46. 47.]
 [48. 49.]
 [50. 51.]
 [52. 53.]
 [54. 55.]
 [56. 57.]
 [58. 59.]
 [60. 61.]
 [62. 63.]
 [64. 65.]
 [66. 67.]
 [68. 69.]
 [70. 71.]
 [72. 73.]
 [74. 75.]
 [76. 77.]
 [78. 79.]
 [80. 81.]
 [82. 83.]
 [84. 85.]
 [86. 87.]
 [88. 89.]
 [90. 91.]
 [92. 93.]
 [94. 95.]
 [96. 97.]
 [98. 99.]]
[[ 0.+0.j  1.+0.j]
 [ 2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j]
 [ 6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j]
 [10.+0.j 11.+0.j]
 [12.+0.j 13.+0.j]
 [14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j]
 [18.+0.j 19.+0.j]
 [20.+0.j 21.+0.j]
 [22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j]
 [26.+0.j 27.+0.j]
 [28.+0.j 29.+0.j]
 [30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j]
 [34.+0.j 35.+0.j]
 [36.+0.j 37.+0.j]
 [38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j]
 [42.+0.j 43.+0.j]
 [44.+0.j 45.+0.j]
 [46.+0.

In [ ]:
# q11: use of zeros and ones function with hstack
zeroes=np.zeros((20,20))
ones=np.ones((20,20))
both=np.hstack((zeroes,ones))
# hstack takes one positional argument
print(both)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# q12: use arange function and lin function to generate 5 types of values
l2=np.arange(1,100,2)
print(type(l2))
# print(l2)
l22=np.linspace(1,5,200)
# print(l22)
l22.reshape(20,10)

<class 'numpy.ndarray'>


array([[1.        , 1.0201005 , 1.04020101, 1.06030151, 1.08040201,
        1.10050251, 1.12060302, 1.14070352, 1.16080402, 1.18090452],
       [1.20100503, 1.22110553, 1.24120603, 1.26130653, 1.28140704,
        1.30150754, 1.32160804, 1.34170854, 1.36180905, 1.38190955],
       [1.40201005, 1.42211055, 1.44221106, 1.46231156, 1.48241206,
        1.50251256, 1.52261307, 1.54271357, 1.56281407, 1.58291457],
       [1.60301508, 1.62311558, 1.64321608, 1.66331658, 1.68341709,
        1.70351759, 1.72361809, 1.74371859, 1.7638191 , 1.7839196 ],
       [1.8040201 , 1.8241206 , 1.84422111, 1.86432161, 1.88442211,
        1.90452261, 1.92462312, 1.94472362, 1.96482412, 1.98492462],
       [2.00502513, 2.02512563, 2.04522613, 2.06532663, 2.08542714,
        2.10552764, 2.12562814, 2.14572864, 2.16582915, 2.18592965],
       [2.20603015, 2.22613065, 2.24623116, 2.26633166, 2.28643216,
        2.30653266, 2.32663317, 2.34673367, 2.36683417, 2.38693467],
       [2.40703518, 2.42713568, 2.4472361

In [ ]:
# q13: find min , max and sum of elements
min=l22.min()
sum=l22.sum()
max=l22.max()
print(min,max,sum)

1.0 5.0 600.0


In [ ]:
#q14: make a 3x3 matrix and print sum across all axises
mat=np.arange(1,10)
mat=mat.reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
sum0=mat.sum(axis=0)
# print(sum0)
sum1=mat.sum(axis=1)
# print(sum1)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(mat[0:1])
print(mat[1:2])
print(mat[2:3])

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [ ]:
print(mat[:,0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
