In [20]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [22]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
for x in np.nditer(a,order='C'):
  print(x)

0
1
16
81
256
625
1296
2401
4096
6561
10000
14641


In [28]:
for x in np.nditer(a, order='F', flags=['external_loop']):
  print(x)


[   0  256 4096]
[   1  625 6561]
[   16  1296 10000]
[   81  2401 14641]


In [30]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...]=x*x
a

array([[                0,                 1,             65536,
                 43046721],
       [       4294967296,      152587890625,     2821109907456,
           33232930569601],
       [  281474976710656,  1853020188851841, 10000000000000000,
        45949729863572161]])

In [32]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [33]:
for x,y  in np.nditer([a,b]):
  print(x,y)

0 3
1 3
65536 3
43046721 3
4294967296 7
152587890625 7
2821109907456 7
33232930569601 7
281474976710656 11
1853020188851841 11
10000000000000000 11
45949729863572161 11
